name: cwi
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - comm=0.2.2
  - debugpy=1.8.14
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - executing=2.2.0
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=9.2.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libcxx=20.1.4
  - libedit=3.1.20191231
  - libexpat=2.7.0
  - libffi=3.4.4
  - libsodium=1.0.20
  - libsqlite=3.45.2
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.5.0
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.1
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.11.8
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pyzmq=26.4.0
  - readline=8.2
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.45.2
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.13.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.6.0
      - adapters==1.2.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.4.0
      - ale-py==0.11.2
      - annotated-types==0.7.0
      - anyio==4.9.0
      - asn1crypto==1.5.1
      - attrs==25.3.0
      - autorom==0.4.2
      - autorom-accept-rom-license==0.6.1
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - blinker==1.9.0
      - boto3==1.40.34
      - botocore==1.40.34
      - brotli==1.1.0
      - cachetools==5.5.2
      - certifi==2025.4.26
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - clarabel==0.10.0
      - click==8.2.1
      - cloudpickle==3.1.1
      - contourpy==1.3.2
      - cryptography==46.0.0
      - cvxpy==1.6.5
      - cycler==0.12.1
      - datadings==3.4.7
      - datasets==3.6.0
      - dill==0.3.8
      - distro==1.9.0
      - farama-notifications==0.0.4
      - fastapi==0.116.1
      - feedparser==6.0.12
      - ffmpy==0.6.0
      - filelock==3.18.0
      - flask==3.1.1
      - flask-cors==6.0.1
      - fonttools==4.57.0
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - func-timeout==4.3.5
      - gdown==5.2.0
      - geodatasets==2024.8.0
      - geopandas==1.1.1
      - google-api-core==2.25.1
      - google-api-python-client==2.182.0
      - google-auth==2.40.3
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.2.2
      - google-cloud-bigquery==3.38.0
      - google-cloud-core==2.4.3
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - gradio==5.38.0
      - gradio-client==1.11.0
      - groovy==0.1.2
      - grpcio==1.75.0
      - grpcio-status==1.75.0
      - gymnasium==1.2.0
      - h11==0.16.0
      - h2==4.3.0
      - hf-xet==1.1.5
      - hpack==4.1.0
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - hyperframe==6.1.0
      - icl-for-rag==0.1.0
      - idna==3.10
      - importlib-resources==6.5.2
      - inquirerpy==0.3.4
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jiter==0.10.0
      - jmespath==1.0.1
      - joblib==1.5.0
      - kaggle==1.7.4.5
      - kiwisolver==1.4.8
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - mlx==0.26.5
      - mlx-lm==0.26.0
      - mlx-metal==0.26.5
      - mpmath==1.3.0
      - msgpack==1.1.1
      - msgpack-numpy==0.4.8
      - multidict==6.6.3
      - multiprocess==0.70.16
      - natsort==8.4.0
      - networkx==3.4.2
      - numpy==2.2.5
      - oauthlib==3.3.1
      - ollama==0.5.1
      - openai==1.82.1
      - opencv-python==4.12.0.88
      - orjson==3.11.0
      - osqp==1.0.3
      - outcome==1.3.0.post0
      - pandas==2.2.3
      - pfzy==0.3.4
      - pictsure==0.1.1
      - pillow==11.2.1
      - pooch==1.8.2
      - portalocker==3.2.0
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==6.31.1
      - pyarrow==20.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygame==2.6.1
      - pyjwt==2.10.1
      - pyobjc==11.1
      - pyobjc-core==11.1
      - pyobjc-framework-accessibility==11.1
      - pyobjc-framework-accounts==11.1
      - pyobjc-framework-addressbook==11.1
      - pyobjc-framework-adservices==11.1
      - pyobjc-framework-adsupport==11.1
      - pyobjc-framework-applescriptkit==11.1
      - pyobjc-framework-applescriptobjc==11.1
      - pyobjc-framework-applicationservices==11.1
      - pyobjc-framework-apptrackingtransparency==11.1
      - pyobjc-framework-audiovideobridging==11.1
      - pyobjc-framework-authenticationservices==11.1
      - pyobjc-framework-automaticassessmentconfiguration==11.1
      - pyobjc-framework-automator==11.1
      - pyobjc-framework-avfoundation==11.1
      - pyobjc-framework-avkit==11.1
      - pyobjc-framework-avrouting==11.1
      - pyobjc-framework-backgroundassets==11.1
      - pyobjc-framework-browserenginekit==11.1
      - pyobjc-framework-businesschat==11.1
      - pyobjc-framework-calendarstore==11.1
      - pyobjc-framework-callkit==11.1
      - pyobjc-framework-carbon==11.1
      - pyobjc-framework-cfnetwork==11.1
      - pyobjc-framework-cinematic==11.1
      - pyobjc-framework-classkit==11.1
      - pyobjc-framework-cloudkit==11.1
      - pyobjc-framework-cocoa==11.1
      - pyobjc-framework-collaboration==11.1
      - pyobjc-framework-colorsync==11.1
      - pyobjc-framework-contacts==11.1
      - pyobjc-framework-contactsui==11.1
      - pyobjc-framework-coreaudio==11.1
      - pyobjc-framework-coreaudiokit==11.1
      - pyobjc-framework-corebluetooth==11.1
      - pyobjc-framework-coredata==11.1
      - pyobjc-framework-corehaptics==11.1
      - pyobjc-framework-corelocation==11.1
      - pyobjc-framework-coremedia==11.1
      - pyobjc-framework-coremediaio==11.1
      - pyobjc-framework-coremidi==11.1
      - pyobjc-framework-coreml==11.1
      - pyobjc-framework-coremotion==11.1
      - pyobjc-framework-coreservices==11.1
      - pyobjc-framework-corespotlight==11.1
      - pyobjc-framework-coretext==11.1
      - pyobjc-framework-corewlan==11.1
      - pyobjc-framework-cryptotokenkit==11.1
      - pyobjc-framework-datadetection==11.1
      - pyobjc-framework-devicecheck==11.1
      - pyobjc-framework-devicediscoveryextension==11.1
      - pyobjc-framework-dictionaryservices==11.1
      - pyobjc-framework-discrecording==11.1
      - pyobjc-framework-discrecordingui==11.1
      - pyobjc-framework-diskarbitration==11.1
      - pyobjc-framework-dvdplayback==11.1
      - pyobjc-framework-eventkit==11.1
      - pyobjc-framework-exceptionhandling==11.1
      - pyobjc-framework-executionpolicy==11.1
      - pyobjc-framework-extensionkit==11.1
      - pyobjc-framework-externalaccessory==11.1
      - pyobjc-framework-fileprovider==11.1
      - pyobjc-framework-fileproviderui==11.1
      - pyobjc-framework-findersync==11.1
      - pyobjc-framework-fsevents==11.1
      - pyobjc-framework-fskit==11.1
      - pyobjc-framework-gamecenter==11.1
      - pyobjc-framework-gamecontroller==11.1
      - pyobjc-framework-gamekit==11.1
      - pyobjc-framework-gameplaykit==11.1
      - pyobjc-framework-healthkit==11.1
      - pyobjc-framework-imagecapturecore==11.1
      - pyobjc-framework-inputmethodkit==11.1
      - pyobjc-framework-installerplugins==11.1
      - pyobjc-framework-instantmessage==11.1
      - pyobjc-framework-intents==11.1
      - pyobjc-framework-intentsui==11.1
      - pyobjc-framework-iobluetooth==11.1
      - pyobjc-framework-iobluetoothui==11.1
      - pyobjc-framework-iosurface==11.1
      - pyobjc-framework-ituneslibrary==11.1
      - pyobjc-framework-kernelmanagement==11.1
      - pyobjc-framework-latentsemanticmapping==11.1
      - pyobjc-framework-launchservices==11.1
      - pyobjc-framework-libdispatch==11.1
      - pyobjc-framework-libxpc==11.1
      - pyobjc-framework-linkpresentation==11.1
      - pyobjc-framework-localauthentication==11.1
      - pyobjc-framework-localauthenticationembeddedui==11.1
      - pyobjc-framework-mailkit==11.1
      - pyobjc-framework-mapkit==11.1
      - pyobjc-framework-mediaaccessibility==11.1
      - pyobjc-framework-mediaextension==11.1
      - pyobjc-framework-medialibrary==11.1
      - pyobjc-framework-mediaplayer==11.1
      - pyobjc-framework-mediatoolbox==11.1
      - pyobjc-framework-metal==11.1
      - pyobjc-framework-metalfx==11.1
      - pyobjc-framework-metalkit==11.1
      - pyobjc-framework-metalperformanceshaders==11.1
      - pyobjc-framework-metalperformanceshadersgraph==11.1
      - pyobjc-framework-metrickit==11.1
      - pyobjc-framework-mlcompute==11.1
      - pyobjc-framework-modelio==11.1
      - pyobjc-framework-multipeerconnectivity==11.1
      - pyobjc-framework-naturallanguage==11.1
      - pyobjc-framework-netfs==11.1
      - pyobjc-framework-network==11.1
      - pyobjc-framework-networkextension==11.1
      - pyobjc-framework-notificationcenter==11.1
      - pyobjc-framework-opendirectory==11.1
      - pyobjc-framework-osakit==11.1
      - pyobjc-framework-oslog==11.1
      - pyobjc-framework-passkit==11.1
      - pyobjc-framework-pencilkit==11.1
      - pyobjc-framework-phase==11.1
      - pyobjc-framework-photos==11.1
      - pyobjc-framework-photosui==11.1
      - pyobjc-framework-preferencepanes==11.1
      - pyobjc-framework-pushkit==11.1
      - pyobjc-framework-quartz==11.1
      - pyobjc-framework-quicklookthumbnailing==11.1
      - pyobjc-framework-replaykit==11.1
      - pyobjc-framework-safariservices==11.1
      - pyobjc-framework-safetykit==11.1
      - pyobjc-framework-scenekit==11.1
      - pyobjc-framework-screencapturekit==11.1
      - pyobjc-framework-screensaver==11.1
      - pyobjc-framework-screentime==11.1
      - pyobjc-framework-scriptingbridge==11.1
      - pyobjc-framework-searchkit==11.1
      - pyobjc-framework-security==11.1
      - pyobjc-framework-securityfoundation==11.1
      - pyobjc-framework-securityinterface==11.1
      - pyobjc-framework-securityui==11.1
      - pyobjc-framework-sensitivecontentanalysis==11.1
      - pyobjc-framework-servicemanagement==11.1
      - pyobjc-framework-sharedwithyou==11.1
      - pyobjc-framework-sharedwithyoucore==11.1
      - pyobjc-framework-shazamkit==11.1
      - pyobjc-framework-social==11.1
      - pyobjc-framework-soundanalysis==11.1
      - pyobjc-framework-speech==11.1
      - pyobjc-framework-spritekit==11.1
      - pyobjc-framework-storekit==11.1
      - pyobjc-framework-symbols==11.1
      - pyobjc-framework-syncservices==11.1
      - pyobjc-framework-systemconfiguration==11.1
      - pyobjc-framework-systemextensions==11.1
      - pyobjc-framework-threadnetwork==11.1
      - pyobjc-framework-uniformtypeidentifiers==11.1
      - pyobjc-framework-usernotifications==11.1
      - pyobjc-framework-usernotificationsui==11.1
      - pyobjc-framework-videosubscriberaccount==11.1
      - pyobjc-framework-videotoolbox==11.1
      - pyobjc-framework-virtualization==11.1
      - pyobjc-framework-vision==11.1
      - pyobjc-framework-webkit==11.1
      - pyogrio==0.11.1
      - pyopenssl==25.3.0
      - pyparsing==3.2.3
      - pyproj==3.7.2
      - pyprojroot==0.3.0
      - pysocks==1.7.1
      - python-dotenv==1.1.0
      - python-graphviz==0.21
      - python-multipart==0.0.20
      - python-slugify==8.0.4
      - pyttsx3==2.99
      - pytz==2025.2
      - pyyaml==6.0.2
      - qdrant-client==1.15.1
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rich==14.0.0
      - rsa==4.9.1
      - ruff==0.12.4
      - s3transfer==0.14.0
      - safehttpx==0.1.6
      - safetensors==0.6.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - scs==3.2.7.post2
      - selenium==4.33.0
      - semantic-version==2.10.0
      - sentence-transformers==5.1.1
      - sgmllib3k==1.0.0
      - shapely==2.1.1
      - shellingham==1.5.4
      - shimmy==2.0.0
      - simplebloom==1.0.6
      - simplejpeg==1.8.2
      - sniffio==1.3.1
      - snowflake==1.7.0
      - snowflake--legacy==1.0.1
      - snowflake-connector-python==3.17.3
      - snowflake-core==1.7.0
      - sortedcontainers==2.4.0
      - soupsieve==2.7
      - sqlglot==27.16.3
      - sqlparse==0.5.3
      - starlette==0.47.2
      - sympy==1.14.0
      - tabreasbench==0.1.0
      - tabresbench==0.1.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - text-unidecode==1.3
      - threadpoolctl==3.6.0
      - timm==1.0.15
      - tokenizers==0.21.1
      - tomlkit==0.13.3
      - torch==2.8.0
      - torchvision==0.23.0
      - torchviz==0.0.3
      - tqdm==4.67.1
      - trackio==0.1.0
      - transformers==4.51.3
      - trio==0.30.0
      - trio-websocket==0.12.2
      - typer==0.16.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uritemplate==4.2.0
      - urllib3==2.4.0
      - uvicorn==0.35.0
      - vizdoom==1.2.4
      - webdriver-manager==4.0.2
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wsproto==1.2.0
      - xxhash==3.5.0
      - yarl==1.20.1
