#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=2
#SBATCH --job-name=TestingExtensions
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6
#SBATCH --time=00:40:00
#SBATCH --array=0-5%2
#SBATCH --output=slurm_output/sql_creation%A.out

module purge
module load 2025
module load Miniconda3/25.5.1-1

cd $HOME/Github/text-to-sql-dataset/
conda env create -f conda-env.yml

source activate cowolff

srun python create_sql_vllm.py --questions_file data/complete/questions.jsonl --model Qwen/Qwen3-32B-FP8 --out data/complete/data_${SLURM_ARRAY_TASK_ID}.jsonl --tp 2 --batch_size 64 --start_index $((SLURM_ARRAY_TASK_ID * 128)) --end_index $((SLURM_ARRAY_TASK_ID * 128 + 128))
