#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=2
#SBATCH --job-name=SchedulingAllSQLGenerations
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=7
#SBATCH --time=06:00:00
#SBATCH --array=0-270%50
#SBATCH --output=slurm_output/sql_creation_%A_%a.out

module purge
module load 2025
module load Miniconda3/25.5.1-1

cd $HOME/Github/text-to-sql-dataset/
conda env create -f conda-env.yml

source activate cowolff

srun python create_sql_vllm.py --questions_file data/questions.jsonl --model Qwen/Qwen3-32B-FP8 --out data/complete/triplets/data_${SLURM_ARRAY_TASK_ID}.jsonl --tp 2 --batch_size 256 --start_index $((SLURM_ARRAY_TASK_ID * 2500)) --end_index $((SLURM_ARRAY_TASK_ID * 2500 + 2500))
