#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=2
#SBATCH --job-name=SQLGenerations
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=01:00:00
#SBATCH --output=slurm_output/sql_creation%A.out

module purge
module load 2025
module load Miniconda3/25.5.1-1

cd $HOME/Github/text-to-sql-dataset/
conda env create -f conda-env.yml

source activate cowolff

srun python create_sql_vllm.py --questions_file data/questions.jsonl --model Qwen/Qwen3-32B-FP8 --out data/data.jsonl --tp 2 --batch_size 128 --start_index 0 --end_index 100
