#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=2
#SBATCH --job-name=TestingExtensions
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6
#SBATCH --time=08:00:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2025
module load Miniconda3/25.5.1-1

cd $HOME/Github/text-to-sql-dataset/
conda env create -f conda-env.yml

source activate cowolff

srun python extend_schemas.py --folder data/test/statements --model Qwen/Qwen3-32B-FP8 --out-dir data/test/extended --tensor_parallel_size 2 --max-batch-size 64
