#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=4
#SBATCH --job-name=TestEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6
#SBATCH --time=00:10:00
#SBATCH --output=slurm_output_%A.out

module purge
module load 2025
module load Miniconda3/25.5.1-1

cd $HOME/Github/text-to-sql-dataset/
conda env create -f conda-env.yml

source activate cowolff

srun python -uc "from vllm import LLM; llm = LLM(model='Qwen/Qwen3-30B-A3B-FP8', tensor_parallel_size=4); print('VLLM loaded on GPUs')"
